GET http://localhost:3001/
Content-Type: application/json
###

GET http://localhost:3001/user
Content-Type: application/json
###

GET http://localhost:3000/
Content-Type: application/json
###

GET http://localhost:3000/user
Content-Type: application/json